import React from 'react';
import { 
  UploadCloud, 
  Zap, 
  BatteryCharging, 
  Activity, 
  BarChart3, 
  ShieldCheck, 
  Clock, 
  Database,
  ArrowRight,
  FileSpreadsheet,
  Layers,
  Sparkles
} from 'lucide-react';
import { KPICard } from '../components/KPICard.jsx';
import { TimeSeriesChart } from '../components/TimeSeriesChart.jsx';
import { MultiParamChart } from '../components/MultiParamChart.jsx';
import { DonutChart } from '../components/DonutChart.jsx';
import { InsightCard } from '../components/InsightCard.jsx';
import { StatisticsTable } from '../components/StatisticsTable.jsx';
import { DataTable } from '../components/DataTable.jsx';

export function Dashboard({
  dataset,
  onOpenUpload,
  onLoadSampleAC,
  onLoadSampleDC,
  onNavigatePage,
  thresholds
}) {
  if (!dataset) {
    return (
      <div className="page-container">
        <div className="welcome-hero master-card animate-fade-in">
          <div className="hero-content">
            <div className="hero-badge">
              <span className="badge badge-ac">MASTER Instrument</span>
              <span className="badge badge-neutral">RP2040 Powered</span>
            </div>

            <h1 className="hero-title">
              Modular Advanced Sensing & Diagnostic Platform
            </h1>

            <p className="hero-desc">
              Upload historical measurement CSV files generated by MASTER's MicroSD data logger to visualize, analyze, and diagnose electrical and physical waveforms against timestamps.
            </p>

            <div className="hero-actions">
              <button 
                type="button" 
                className="btn btn-lg btn-primary"
                onClick={onOpenUpload}
              >
                <UploadCloud size={18} />
                <span>Upload Measurement CSV</span>
              </button>

              <button 
                type="button" 
                className="btn btn-lg btn-secondary"
                onClick={onLoadSampleAC}
              >
                <Zap size={18} className="text-primary" />
                <span>Load Sample AC Dataset</span>
              </button>

              <button 
                type="button" 
                className="btn btn-lg btn-secondary"
                onClick={onLoadSampleDC}
              >
                <BatteryCharging size={18} className="text-cyan" />
                <span>Load Sample DC Dataset</span>
              </button>
            </div>

            <div className="hero-features-grid">
              <div className="feature-item">
                <Zap size={20} className="text-primary" />
                <div>
                  <h4 className="feat-title">AC Electrical Suite</h4>
                  <p className="feat-desc">RMS Voltage, Current, Active Power, Power Factor & Frequency</p>
                </div>
              </div>

              <div className="feature-item">
                <BatteryCharging size={20} className="text-cyan" />
                <div>
                  <h4 className="feat-title">DC Power & Energy</h4>
                  <p className="feat-desc">Bus Voltage, Current, Power dissipation & Accumulated Energy (Wh)</p>
                </div>
              </div>

              <div className="feature-item">
                <ShieldCheck size={20} className="text-success" />
                <div>
                  <h4 className="feat-title">Stability & Thresholds</h4>
                  <p className="feat-desc">±2% regulation categorization & configurable warning alarms</p>
                </div>
              </div>

              <div className="feature-item">
                <Sparkles size={20} className="text-accent-purple" />
                <div>
                  <h4 className="feat-title">Diagnostic Insights</h4>
                  <p className="feat-desc">Automated data-driven engineering observations and PDF reports</p>
                </div>
              </div>
            </div>
          </div>
        </div>

        <style>{`
          .welcome-hero {
            padding: 48px 36px;
            background: linear-gradient(180deg, #ffffff 0%, #f8fafc 100%);
            border: 1px solid var(--border-light);
            margin-top: 20px;
          }

          .hero-badge {
            display: flex;
            align-items: center;
            gap: 8px;
            margin-bottom: 16px;
          }

          .hero-title {
            font-size: 32px;
            font-weight: 800;
            color: var(--text-primary);
            max-width: 800px;
            line-height: 1.2;
            margin-bottom: 12px;
          }

          .hero-desc {
            font-size: 15px;
            color: var(--text-secondary);
            max-width: 720px;
            line-height: 1.6;
            margin-bottom: 28px;
          }

          .hero-actions {
            display: flex;
            align-items: center;
            gap: 14px;
            flex-wrap: wrap;
            margin-bottom: 40px;
          }

          .hero-features-grid {
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(260px, 1fr));
            gap: 20px;
            padding-top: 32px;
            border-top: 1px solid var(--border-light);
          }

          .feature-item {
            display: flex;
            align-items: flex-start;
            gap: 14px;
          }

          .feat-title {
            font-size: 14px;
            font-weight: 700;
            color: var(--text-primary);
            margin-bottom: 3px;
          }

          .feat-desc {
            font-size: 12px;
            color: var(--text-muted);
            line-height: 1.4;
          }
        `}</style>
      </div>
    );
  }

  const { type, metrics, cleanData, downsampledData, detectedParameters, stability, conditionDistribution, insights, fileName, timeRange } = dataset;

  // Decide primary parameters based on type
  const primaryParam = detectedParameters.includes('voltage') ? 'voltage' : (detectedParameters[0] || 'current');
  const secondaryParam = detectedParameters.includes('current') ? 'current' : (detectedParameters[1] || 'power');

  return (
    <div className="page-container animate-fade-in">
      {/* Page Header */}
      <div className="page-header">
        <div className="page-title-group">
          <h1>
            MASTER Diagnostic Dashboard
            <span className={`badge ${type === 'AC' ? 'badge-ac' : 'badge-dc'}`}>
              {type} Measurement
            </span>
          </h1>
          <p>
            Historical measurement analysis from MASTER's MicroSD data logger • <strong>{fileName}</strong>
          </p>
        </div>

        <div className="page-actions">
          <button 
            type="button" 
            className="btn btn-secondary"
            onClick={() => onNavigatePage(type === 'AC' ? 'ac-analysis' : 'dc-analysis')}
          >
            <span>Open {type} Analysis Suite</span>
            <ArrowRight size={14} />
          </button>
          <button 
            type="button" 
            className="btn btn-primary"
            onClick={onOpenUpload}
          >
            <UploadCloud size={14} />
            <span>Upload New CSV</span>
          </button>
        </div>
      </div>

      {/* Dataset Summary Banner */}
      <div className="dataset-overview-bar master-card">
        <div className="dob-item">
          <span className="dob-label">File Name</span>
          <span className="dob-value mono">{fileName}</span>
        </div>
        <div className="dob-divider"></div>
        <div className="dob-item">
          <span className="dob-label">Records Logged</span>
          <span className="dob-value mono">{cleanData.length.toLocaleString()} samples</span>
        </div>
        <div className="dob-divider"></div>
        <div className="dob-item">
          <span className="dob-label">Time Window</span>
          <span className="dob-value mono">{timeRange.startTime} – {timeRange.endTime}</span>
        </div>
        <div className="dob-divider"></div>
        <div className="dob-item">
          <span className="dob-label">Session Duration</span>
          <span className="dob-value mono">{timeRange.durationFormatted}</span>
        </div>
      </div>

      {/* KPI Cards Grid */}
      <div className="kpi-grid">
        {type === 'AC' ? (
          <>
            <KPICard paramKey="voltage" stats={metrics.voltage} datasetType="AC" />
            <KPICard paramKey="current" stats={metrics.current} datasetType="AC" />
            <KPICard paramKey="power" stats={metrics.power} datasetType="AC" />
            <KPICard paramKey="powerFactor" stats={metrics.powerFactor} datasetType="AC" />
            <KPICard paramKey="frequency" stats={metrics.frequency} datasetType="AC" />
          </>
        ) : (
          <>
            <KPICard paramKey="voltage" stats={metrics.voltage} datasetType="DC" />
            <KPICard paramKey="current" stats={metrics.current} datasetType="DC" />
            <KPICard paramKey="power" stats={metrics.power} datasetType="DC" />
            <KPICard paramKey="energy" stats={metrics.energy} datasetType="DC" />
          </>
        )}
      </div>

      {/* Primary Charts Row */}
      <div className="charts-grid-2">
        <TimeSeriesChart 
          data={downsampledData} 
          paramKey={primaryParam} 
          datasetType={type} 
          thresholds={thresholds}
        />
        <TimeSeriesChart 
          data={downsampledData} 
          paramKey={secondaryParam} 
          datasetType={type} 
          thresholds={thresholds}
        />
      </div>

      {/* Multi-Parameter Synchronized Chart */}
      <div style={{ marginBottom: 24 }}>
        <MultiParamChart 
          data={downsampledData}
          detectedParameters={detectedParameters}
          datasetType={type}
        />
      </div>

      {/* Stability & Operating Conditions Donut Charts */}
      <div className="charts-grid-2">
        <DonutChart 
          type="stability" 
          data={stability} 
          title="Measurement Stability Index" 
          subtitle="Proportion of samples maintaining ±2% regulation tolerance"
        />
        <DonutChart 
          type="operating" 
          data={conditionDistribution} 
          title="Operating Condition Distribution" 
          subtitle="Classification against safety & performance thresholds"
        />
      </div>

      {/* Automated Diagnostic Insights */}
      <div style={{ marginBottom: 24 }}>
        <InsightCard insights={insights} />
      </div>

      {/* Statistics Table */}
      <div style={{ marginBottom: 24 }}>
        <StatisticsTable 
          metrics={metrics} 
          detectedParameters={detectedParameters} 
          datasetType={type} 
          fileName={fileName}
        />
      </div>

      {/* Data Table */}
      <div style={{ marginBottom: 24 }}>
        <DataTable 
          cleanData={cleanData} 
          detectedParameters={detectedParameters} 
          datasetType={type} 
          fileName={fileName}
        />
      </div>

      <style>{`
        .dataset-overview-bar {
          display: flex;
          align-items: center;
          justify-content: space-between;
          padding: 14px 20px;
          margin-bottom: 24px;
          flex-wrap: wrap;
          gap: 12px;
          background: #ffffff;
        }

        .dob-item {
          display: flex;
          flex-direction: column;
        }

        .dob-label {
          font-size: 11px;
          font-weight: 600;
          color: var(--text-muted);
          text-transform: uppercase;
        }

        .dob-value {
          font-size: 13.5px;
          font-weight: 700;
          color: var(--text-primary);
        }

        .dob-divider {
          width: 1px;
          height: 28px;
          background: var(--border-light);
        }

        @media (max-width: 768px) {
          .dob-divider {
            display: none;
          }
        }
      `}</style>
    </div>
  );
}
