import React from 'react';
import { 
  UploadCloud, 
  FileSpreadsheet, 
  HelpCircle, 
  CheckCircle2, 
  Zap, 
  BatteryCharging, 
  HardDrive,
  Info,
  ArrowRight
} from 'lucide-react';
import { FileUploader } from '../components/FileUploader.jsx';

export function UploadPage({
  onDatasetLoaded,
  onLoadSampleAC,
  onLoadSampleDC,
  activeDataset,
  onNavigatePage
}) {
  return (
    <div className="page-container animate-fade-in">
      {/* Header */}
      <div className="page-header">
        <div className="page-title-group">
          <h1>
            <UploadCloud size={22} className="text-primary" />
            MASTER MicroSD Data Upload Center
          </h1>
          <p>
            Upload measurement logs generated by MASTER onto a FAT32 MicroSD card (.csv format)
          </p>
        </div>

        {activeDataset && (
          <div className="page-actions">
            <button 
              type="button" 
              className="btn btn-primary"
              onClick={() => onNavigatePage(activeDataset.type === 'AC' ? 'ac-analysis' : 'dc-analysis')}
            >
              <span>View {activeDataset.type} Analysis</span>
              <ArrowRight size={14} />
            </button>
          </div>
        )}
      </div>

      {/* Main Uploader Box */}
      <div style={{ marginBottom: 24 }}>
        <FileUploader 
          onDatasetLoaded={onDatasetLoaded}
          onLoadSampleAC={onLoadSampleAC}
          onLoadSampleDC={onLoadSampleDC}
          activeDataset={activeDataset}
        />
      </div>

      {/* Schema Reference & Column Aliases Guide */}
      <div className="master-card schema-guide-card">
        <div className="card-header-row">
          <div className="card-header-title">
            <FileSpreadsheet size={18} className="text-primary" />
            MASTER CSV Schema & Header Compatibility Guide
          </div>
          <span className="badge badge-neutral">Smart Auto-Detection</span>
        </div>

        <p style={{ fontSize: 13, color: 'var(--text-secondary)', marginBottom: 16 }}>
          MASTER automatically matches standard sensor columns and aliases. Headers are case-insensitive and resilient to extra whitespace or symbols.
        </p>

        <div className="schema-grid">
          <div className="schema-column-box">
            <div className="schema-box-header">
              <Zap size={15} className="text-primary" />
              <span className="box-title">AC Electrical Log Schema</span>
            </div>
            <table className="schema-table">
              <thead>
                <tr>
                  <th>Field</th>
                  <th>Accepted Header Aliases</th>
                  <th>Unit</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <td className="field-name">Timestamp</td>
                  <td className="aliases mono">Timestamp, time, datetime, t</td>
                  <td className="unit mono">HH:MM:SS</td>
                </tr>
                <tr>
                  <td className="field-name">Voltage</td>
                  <td className="aliases mono">Voltage, V, RMS_Voltage, V_RMS</td>
                  <td className="unit mono">V (Volts)</td>
                </tr>
                <tr>
                  <td className="field-name">Current</td>
                  <td className="aliases mono">Current, I, RMS_Current, I_RMS</td>
                  <td className="unit mono">A (Amperes)</td>
                </tr>
                <tr>
                  <td className="field-name">Active Power</td>
                  <td className="aliases mono">Power, P, Active_Power, P_W</td>
                  <td className="unit mono">W (Watts)</td>
                </tr>
                <tr>
                  <td className="field-name">Power Factor</td>
                  <td className="aliases mono">PowerFactor, PF, cos_phi, p_factor</td>
                  <td className="unit mono">0.0 – 1.0</td>
                </tr>
                <tr>
                  <td className="field-name">Frequency</td>
                  <td className="aliases mono">Frequency, freq, Hz, f</td>
                  <td className="unit mono">Hz (Hertz)</td>
                </tr>
              </tbody>
            </table>
          </div>

          <div className="schema-column-box">
            <div className="schema-box-header">
              <BatteryCharging size={15} className="text-cyan" />
              <span className="box-title">DC Power & Energy Schema</span>
            </div>
            <table className="schema-table">
              <thead>
                <tr>
                  <th>Field</th>
                  <th>Accepted Header Aliases</th>
                  <th>Unit</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <td className="field-name">Timestamp</td>
                  <td className="aliases mono">Timestamp, time, datetime, t</td>
                  <td className="unit mono">HH:MM:SS</td>
                </tr>
                <tr>
                  <td className="field-name">Voltage</td>
                  <td className="aliases mono">Voltage, V, DC_Voltage, Vdc</td>
                  <td className="unit mono">V (Volts)</td>
                </tr>
                <tr>
                  <td className="field-name">Current</td>
                  <td className="aliases mono">Current, I, DC_Current, Idc</td>
                  <td className="unit mono">A (Amperes)</td>
                </tr>
                <tr>
                  <td className="field-name">Power</td>
                  <td className="aliases mono">Power, P, DC_Power, Watts</td>
                  <td className="unit mono">W (Watts)</td>
                </tr>
                <tr>
                  <td className="field-name">Energy</td>
                  <td className="aliases mono">Energy, Wh, kWh, Accum_Wh</td>
                  <td className="unit mono">Wh (Watt-hrs)</td>
                </tr>
                <tr>
                  <td className="field-name">Aux Sensors</td>
                  <td className="aliases mono">Temperature, RPM, Distance_mm</td>
                  <td className="unit mono">°C / RPM / mm</td>
                </tr>
              </tbody>
            </table>
          </div>
        </div>

        <div className="microSD-format-tip">
          <HardDrive size={16} className="text-primary" />
          <span>
            <strong>MicroSD Card Tip:</strong> MASTER writes CSV data directly using SPI DMA onto standard FAT32 formatted MicroSD cards. File naming follows standard format <code className="inline-code">AC_001.csv</code> or <code className="inline-code">DC_001.csv</code>.
          </span>
        </div>
      </div>

      <style>{`
        .schema-grid {
          display: grid;
          grid-template-columns: repeat(auto-fit, minmax(360px, 1fr));
          gap: 16px;
          margin-bottom: 16px;
        }

        .schema-column-box {
          background: var(--bg-subtle);
          border: 1px solid var(--border-light);
          border-radius: var(--radius-md);
          overflow: hidden;
        }

        .schema-box-header {
          display: flex;
          align-items: center;
          gap: 8px;
          padding: 10px 14px;
          background: #ffffff;
          border-bottom: 1px solid var(--border-light);
        }

        .box-title {
          font-size: 13px;
          font-weight: 700;
          color: var(--text-primary);
        }

        .schema-table {
          width: 100%;
          border-collapse: collapse;
          font-size: 12px;
        }

        .schema-table th {
          background: var(--bg-subtle);
          text-align: left;
          padding: 8px 12px;
          border-bottom: 1px solid var(--border-light);
          color: var(--text-secondary);
          font-weight: 600;
        }

        .schema-table td {
          padding: 8px 12px;
          border-bottom: 1px solid var(--border-subtle);
        }

        .field-name {
          font-weight: 600;
          color: var(--text-primary);
        }

        .aliases {
          color: var(--text-secondary);
          font-size: 11.5px;
        }

        .unit {
          color: var(--text-muted);
          font-size: 11px;
        }

        .microSD-format-tip {
          display: flex;
          align-items: center;
          gap: 10px;
          padding: 12px 14px;
          background: var(--primary-light);
          border: 1px solid var(--primary-border);
          border-radius: var(--radius-md);
          font-size: 12.5px;
          color: var(--text-secondary);
        }

        .inline-code {
          font-family: var(--font-mono);
          background: #ffffff;
          padding: 2px 6px;
          border-radius: 4px;
          border: 1px solid #bfdbfe;
          color: var(--primary);
          font-weight: 600;
        }
      `}</style>
    </div>
  );
}
